MPICXX = mpiicpc

REPORTFLAGS = -vec-report1
CXXFLAGS = -ipo -O3 -no-prec-div -xHost -static-intel \
	   -fopenmp \
	   -g -Wall -DMPICH_IGNORE_CXX_SEEK -DNDEBUG

#DIALECTFLAGS = -masm=intel
ASMFLAGS = -fsource-asm $(DIALECTFLAGS)


include Makefile

%.s: %.cc
	$(MPICXX) $(CXXFLAGS) $(ASMFLAGS) -S $<

pmt: main.o cart.o node.o output.o
	$(MPICXX) $(CXXFLAGS) $(REPORTFLAGS) -o $@ $^ $(LIBS)
